version: 1

formatters:
  colored_formatter:
    class: "colorlog.ColoredFormatter"
    format: "%(log_color)s%(levelname)-7s%(reset)s | %(black)s%(asctime)s | %(threadName)s | %(name)s | %(message)s"
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    formatter: colored_formatter

loggers:
  markone:
    handlers: [console]
    level: DEBUG
    propagate: no

root:
  handlers: [console]
  level: INFO
